# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ujSjWM_qovy38YtWOGeabaDc2ryFsP7l
"""

# Alexander J. Jackson
# for_vowels.py

how_many = input("Please enter a string: ")
vowels = "aeiou"
count = 0


for i in how_many:
  if i in vowels:
    count += 1
print(f"number of vowels in input {how_many} is: {count}")